language: ruby
before_install:
  - gem install bundler

notifications:
  email:
  - ngiger@ywesee.com
  - zdavatz@ywesee.com
rvm:
  - ruby-head
  - 2.1.2
  - 2.0.0
  - 1.9.3
  - 1.8.7
matrix:
  allow_failures:
    - rvm: ruby-head
