language: ruby
cache: bundler
bundler_args: --without debugger

notifications:
  email:
  - ngiger@ywesee.com
  - zdavatz@ywesee.com
rvm:
  - ruby-head
  - 2.2.3
  - 2.1.2
  - 2.0.0
  - 1.9.3
matrix:
  allow_failures:
    - rvm: ruby-head
